# Clear only generated asset trees so removed source assets do not ship in
# incremental builds. The app's writable Documents directory is unrelated.
foreach(_required SOURCE_DIR SKINS_DIR SONGS_DIR DEST_DIR)
  if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
    message(FATAL_ERROR "ios_assets.cmake requires -D${_required}=<path>")
  endif()
  if(NOT IS_ABSOLUTE "${${_required}}")
    message(FATAL_ERROR "${_required} must be an absolute path (got '${${_required}}')")
  endif()
endforeach()
set(SKINS_DEST_DIR "${DEST_DIR}/Skins")
include("${CMAKE_CURRENT_LIST_DIR}/package_skins.cmake")
file(REMOVE_RECURSE "${DEST_DIR}/Songs" "${DEST_DIR}/shader")
file(MAKE_DIRECTORY "${DEST_DIR}")
file(COPY "${SOURCE_DIR}/LICENSE" "${SOURCE_DIR}/NOTICE" DESTINATION "${DEST_DIR}")
file(COPY "${SOURCE_DIR}/shader" DESTINATION "${DEST_DIR}")
file(COPY "${SONGS_DIR}/" DESTINATION "${DEST_DIR}/Songs" PATTERN ".git*" EXCLUDE)
file(READ "${SOURCE_DIR}/config.toml" _config)
string(REGEX REPLACE "(^|\n)([ \t]*)touch_input[ \t]*=[ \t]*false" "\\1\\2touch_input = true" _config "${_config}")
string(REGEX REPLACE "(^|\n)([ \t]*)vsync[ \t]*=[ \t]*false" "\\1\\2vsync = true" _config "${_config}")
foreach(_expected "touch_input = true" "vsync = true")
  if(NOT _config MATCHES "${_expected}")
    message(FATAL_ERROR "config.toml no longer contains an overridable '${_expected}' entry; update ios_assets.cmake")
  endif()
endforeach()
file(WRITE "${DEST_DIR}/config.toml" "${_config}")

# Runtime compares this small token instead of traversing shader files on launch.
file(GLOB_RECURSE _shader_files RELATIVE "${SOURCE_DIR}/shader" "${SOURCE_DIR}/shader/*")
list(SORT _shader_files)
set(_shader_manifest "")
foreach(_shader IN LISTS _shader_files)
  file(SHA256 "${SOURCE_DIR}/shader/${_shader}" _shader_hash)
  string(APPEND _shader_manifest "${_shader}:${_shader_hash}\n")
endforeach()
string(SHA256 _shader_version "${_shader_manifest}")
file(WRITE "${DEST_DIR}/.shader-version" "${_shader_version}\n")
