# Shared by desktop release packaging and ios_assets.cmake. Only the generated
# destination is replaced; source skins and installed user data are untouched.
foreach(_required SKINS_DIR SKINS_DEST_DIR)
  if(NOT DEFINED ${_required} OR NOT IS_ABSOLUTE "${${_required}}")
    message(FATAL_ERROR "package_skins.cmake requires -D${_required}=<absolute path>")
  endif()
endforeach()
if(NOT DEFINED OURTAIKO_SKIN_PROFILE)
  if(DEFINED ENV{OURTAIKO_SKIN_PROFILE})
    set(OURTAIKO_SKIN_PROFILE "$ENV{OURTAIKO_SKIN_PROFILE}")
  else()
    set(OURTAIKO_SKIN_PROFILE green)
  endif()
endif()
if(NOT OURTAIKO_SKIN_PROFILE MATCHES "^[a-zA-Z0-9_-]+$")
  message(FATAL_ERROR "Invalid skin profile: '${OURTAIKO_SKIN_PROFILE}'")
endif()
set(_skin_manifest "${CMAKE_CURRENT_LIST_DIR}/../packaging/skins-${OURTAIKO_SKIN_PROFILE}.txt")
file(STRINGS "${_skin_manifest}" _packaged_skins)
if(NOT _packaged_skins)
  message(FATAL_ERROR "Skin profile must contain at least one skin: ${_skin_manifest}")
endif()
foreach(_skin IN LISTS _packaged_skins)
  if(NOT _skin MATCHES "^[a-zA-Z0-9_-]+$")
    message(FATAL_ERROR "Invalid skin directory name: '${_skin}'")
  endif()
  if(NOT EXISTS "${SKINS_DIR}/${_skin}/Graphics/skin_config.json")
    message(FATAL_ERROR "Missing ${_skin} assets required by skin profile '${OURTAIKO_SKIN_PROFILE}'")
  endif()
endforeach()

# Refuse overlapping source/destination trees before removing generated assets.
get_filename_component(_skins_source "${SKINS_DIR}" REALPATH)
get_filename_component(_skins_dest "${SKINS_DEST_DIR}" REALPATH)
file(RELATIVE_PATH _dest_from_source "${_skins_source}" "${_skins_dest}")
file(RELATIVE_PATH _source_from_dest "${_skins_dest}" "${_skins_source}")
if(NOT _dest_from_source MATCHES "^\\.\\./" OR NOT _source_from_dest MATCHES "^\\.\\./")
  message(FATAL_ERROR "Skin source and generated destination must not overlap")
endif()
file(REMOVE_RECURSE "${SKINS_DEST_DIR}")
file(MAKE_DIRECTORY "${SKINS_DEST_DIR}")
foreach(_skin IN LISTS _packaged_skins)
  file(COPY "${SKINS_DIR}/${_skin}" DESTINATION "${SKINS_DEST_DIR}"
    PATTERN ".git*" EXCLUDE PATTERN ".DS_Store" EXCLUDE)
endforeach()
message(STATUS "Packaged skin profile '${OURTAIKO_SKIN_PROFILE}': ${_packaged_skins}")
